### ISSUE TITLE
Please support to provide document on how to train/generate db for solver!

### ISSUE THREAD

**Issue by vikbeo** [skotz/captcha-breaking-library#9]
Thank Skotz for your very good lib.

I'm working on an captcha which I can work on the filter to have clean final image but currently I don't see how to train the solver and get db?

Actually I have just read previous Issue ticket but not sure how to implement the training properly.

Such as we need to change script to Train & Save instead of Solve?
TRAIN, "I:\qqq"
SAVE, I:\qqq\new.db"

I do see we need a test pool of as big as possible images but how can tell Solver which is good which is bad?

On your script in previous Issue:
TRAIN, "qqq"
FULLTEST, "qqq", "test.txt"

I even see the result: TOTAL CORRECT: 213 (213/266 = 80.08%)

Is that we are manually calculate or the lib support that?

Thank for your support in advanced.

My script.
SetMode,        all
SetupSegmenter, BLOB, 30, 40, 4
SetupSolver,    BVS, "ABCDEFGHIJKLMNOPQRSTUVWXYZ", 50, 60

DefinePreconditions
   Resize, 400, 140
   RemoveSmallBlobs, 10, 4, 4
   BlackAndWhite
   Grow
   Grow
   Median
EndPreconditions

Solve, %IMAGE%

**Comment by skotz** [comment]
I just put together some new documentation to walk you through how to train a model. Please let me know if any parts are confusing and I'll try to update it accordingly.

Check out the [solver walkthrough](https://github.com/skotz/captcha-breaking-library/blob/master/Examples/Color%20CAPTCHA/readme.md).

Thanks!

**Comment by skotz** [comment]
And here's a link to the folder with a working example and training scripts.

https://github.com/skotz/captcha-breaking-library/tree/master/Examples/Color%20CAPTCHA

**Comment by vikbeo** [comment]
Great. The route is much clearer! Thank a lot for your helpful lib and kind support.
